FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

COPY socialhub_api-master/pom.xml .
COPY socialhub_api-master/src ./src

RUN apk add --no-cache maven
RUN mvn clean package -DskipTests

EXPOSE 8080

CMD ["java", "-jar", "target/socialhub_api-0.0.1-SNAPSHOT.jar"]
